# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

expandedjamesonC_get_output <- function() {
    .Call('_qraLm_expandedjamesonC_get_output', PACKAGE = 'qraLm')
}

expandedjamesonC_set_state <- function(new_state) {
    invisible(.Call('_qraLm_expandedjamesonC_set_state', PACKAGE = 'qraLm', new_state))
}

expandedjamesonC_get_state <- function() {
    .Call('_qraLm_expandedjamesonC_get_state', PACKAGE = 'qraLm')
}

expandedjamesonC_reset_observer <- function() {
    invisible(.Call('_qraLm_expandedjamesonC_reset_observer', PACKAGE = 'qraLm'))
}

expandedjamesonC_adap <- function(init, duration, step_size = 1.0, start = 0.0) {
    .Call('_qraLm_expandedjamesonC_adap', PACKAGE = 'qraLm', init, duration, step_size, start)
}

expandedjamesonC_at <- function(init, times, step_size = 1.0, start = 0.0) {
    .Call('_qraLm_expandedjamesonC_at', PACKAGE = 'qraLm', init, times, step_size, start)
}

expandedjamesonC_continue_at <- function(times, step_size = 1.0) {
    .Call('_qraLm_expandedjamesonC_continue_at', PACKAGE = 'qraLm', times, step_size)
}

#' Integrate the growth model with Jameson effect
#' 
#' This function integrate the Jameson model through ODE. See \link{sfGrowthJameson}.
#'
#' @param init initial values
#' @param duration the end of the integration
#' @param step_size the step size of the integration
#' @param start start of the integration
#' @export
expandedjamesonC <- function(init, duration, step_size = 1.0, start = 0.0) {
    .Call('_qraLm_expandedjamesonC', PACKAGE = 'qraLm', init, duration, step_size, start)
}

expandedjamesonC_no_record <- function(init, duration, step_size = 1.0, start = 0.0) {
    .Call('_qraLm_expandedjamesonC_no_record', PACKAGE = 'qraLm', init, duration, step_size, start)
}

#' Set the parameters to integrate the growth model with Jameson effect
#' 
#' This function set the parameters to integrate the Jameson model through ODE. See \link{sfGrowthJameson}.
#'
#' @param mumax1 mumax (/h) of the first population
#' @param mumax2 mumax (/h) of the second population
#' @param ymax1 MPD (CFU) of the first population
#' @param ymax2 MPD (CFU) of the second population
#' @param gamma interaction
#' @export
expandedjamesonC_set_params <- function(mumax1 = 0.14, mumax2 = 0.3, ymax1 = 1e+08, ymax2 = 1e+07, gamma = 1) {
    invisible(.Call('_qraLm_expandedjamesonC_set_params', PACKAGE = 'qraLm', mumax1, mumax2, ymax1, ymax2, gamma))
}

expandedjamesonC_get_params <- function() {
    .Call('_qraLm_expandedjamesonC_get_params', PACKAGE = 'qraLm')
}

